---   # rust-tapyruscore-rpc CI: If you edit this file please update README.md
on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - 'test-ci/**'
  pull_request:

name: Continuous integration

jobs:
  # Stable:                       # 2 jobs, one per lock file.
  #   name: Test - stable toolchain
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       dep: [minimal, recent]
  #   steps:
  #     - name: "Checkout repo"
  #       uses: actions/checkout@v4
  #     - name: "Checkout maintainer tools"
  #       uses: actions/checkout@v4
  #       with:
  #         repository: rust-bitcoin/rust-bitcoin-maintainer-tools
  #         rev: b2ac115
  #         path: maintainer-tools
  #     - name: "Select toolchain"
  #       uses: dtolnay/rust-toolchain@stable
  #     - name: "Set dependencies"
  #       run: cp Cargo-${{ matrix.dep }}.lock Cargo.lock
  #     - name: "Run test script"
  #       run: ./maintainer-tools/ci/run_task.sh stable

  # Nightly:                      #  2 jobs, one per lock file.
  #   name: Test - nightly toolchain
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       dep: [minimal, recent]
  #   steps:
  #     - name: "Checkout repo"
  #       uses: actions/checkout@v4
  #     - name: "Checkout maintainer tools"
  #       uses: actions/checkout@v4
  #       with:
  #         repository: rust-bitcoin/rust-bitcoin-maintainer-tools
  #         rev: b2ac115
  #         path: maintainer-tools
  #     - name: "Select toolchain"
  #       uses: dtolnay/rust-toolchain@nightly
  #     - name: "Set dependencies"
  #       run: cp Cargo-${{ matrix.dep }}.lock Cargo.lock
  #     - name: "Run test script"
  #       run: ./maintainer-tools/ci/run_task.sh nightly

  # MSRV:          # 2 jobs, one per lock file.
  #   name: Test - 1.56.1 toolchain
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       dep: [minimal, recent]
  #   steps:
  #     - name: "Checkout repo"
  #       uses: actions/checkout@v4
  #     - name: "Checkout maintainer tools"
  #       uses: actions/checkout@v4
  #       with:
  #         repository: rust-bitcoin/rust-bitcoin-maintainer-tools
  #         rev: b2ac115
  #         path: maintainer-tools
  #     - name: "Select toolchain"
  #       uses: dtolnay/rust-toolchain@stable
  #       with:
  #         toolchain: "1.56.1"
  #     - name: "Set dependencies"
  #       run: cp Cargo-${{ matrix.dep }}.lock Cargo.lock
  #     - name: "Run test script"
  #       run: ./maintainer-tools/ci/run_task.sh msrv

  Integration:                  # 1 job for each Bitcoin Core version.
    name: Integration tests - stable toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tapyrusversion:
          [
            "0.5.1",
            "0.5.2",
          ]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@stable
      - name: "Run integration tests"
        env:
          TAPYRUSVERSION: ${{ matrix.tapyrusversion }}
          NETWORK_ID: 1905960821
          GENESIS_BLOCK_WITH_SIG: 0100000000000000000000000000000000000000000000000000000000000000000000002b5331139c6bc8646bb4e5737c51378133f70b9712b75548cb3c05f9188670e7440d295e7300c5640730c4634402a3e66fb5d921f76b48d8972a484cc0361e66ef74f45e012103af80b90d25145da28c583359beb47b21796b2fe1a23c1511e443e7a64dfdb27d40e05f064662d6b9acf65ae416379d82e11a9b78cdeb3a316d1057cd2780e3727f70a61f901d10acbe349cd11e04aa6b4351e782c44670aefbe138e99a5ce75ace01010000000100000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0100f2052a010000001976a91445d405b9ed450fec89044f9b7a99a4ef6fe2cd3f88ac00000000
          PRIVATE_KEY: cUJN5RVzYWFoeY8rUztd47jzXCu1p57Ay8V7pqCzsBD3PEXN7Dd4
          ARCH: x86_64
        run: ./contrib/integration_test.sh
